# Generated by Django 4.2.16 on 2024-11-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('playing', 'Playing'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='waiting', max_length=10),
        ),
    ]
