# Generated by Django 4.2.16 on 2024-11-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercard',
            name='is_disqualified',
            field=models.BooleanField(default=False),
        ),
    ]
