# Generated by Django 4.2.16 on 2024-11-15 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_playercard_is_disqualified'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='game',
            table='games',
        ),
        migrations.AlterModelTable(
            name='playercard',
            table='player_cards',
        ),
    ]
